import FanZonesClient from './FanZonesClient'
import type { FanZone } from '@/types/fanzone'

// Mock data for demo - In production, fetch from Supabase
const mockFanZones: FanZone[] = [
  {
    id: 'fz-1',
    name: 'Le Comptoir du Sport',
    city: 'Paris',
    address: '15 Rue de Rivoli, 75001 Paris',
    lat: 48.8566,
    lng: 2.3522,
    teamName: 'Paris Saint-Germain',
    teamLogo: '🔵',
    description: 'Le QG des supporters parisiens avec écran géant et ambiance garantie pour tous les matchs du PSG.',
    capacity: 200,
    amenities: ['screen', 'bar', 'food', 'wifi'],
    openingHours: '17h-02h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-2',
    name: 'La Brasserie Olympique',
    city: 'Marseille',
    address: '42 Quai du Port, 13002 Marseille',
    lat: 43.2965,
    lng: 5.3698,
    teamName: 'Olympique de Marseille',
    teamLogo: '⚪',
    description: 'Institution marseillaise depuis 1987. Vue sur le Vieux-Port et ambiance chaleureuse.',
    capacity: 350,
    amenities: ['screen', 'bar', 'food', 'terrace'],
    openingHours: '11h-01h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-3',
    name: 'Le Repaire des Gones',
    city: 'Lyon',
    address: '8 Place Bellecour, 69002 Lyon',
    lat: 45.7640,
    lng: 4.8357,
    teamName: 'Olympique Lyonnais',
    teamLogo: '🦁',
    description: 'Bar à thème OL avec maillots historiques et retransmission de tous les matchs.',
    capacity: 150,
    amenities: ['screen', 'bar', 'food', 'wifi'],
    openingHours: '16h-00h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-4',
    name: 'Le Chaudron Vert',
    city: 'Saint-Étienne',
    address: '25 Place Jean Jaurès, 42000 Saint-Étienne',
    lat: 45.4397,
    lng: 4.3872,
    teamName: 'AS Saint-Étienne',
    teamLogo: '💚',
    description: 'L\'antre des supporters stéphanois. Décoration unique avec reliques du club.',
    capacity: 180,
    amenities: ['screen', 'bar', 'terrace', 'parking'],
    openingHours: '15h-01h',
    isVerified: false,
    isActive: true,
  },
  {
    id: 'fz-5',
    name: 'Le Café des Dogues',
    city: 'Lille',
    address: '12 Grand Place, 59000 Lille',
    lat: 50.6292,
    lng: 3.0573,
    teamName: 'LOSC Lille',
    teamLogo: '🐕',
    description: 'En plein cœur de Lille, le point de ralliement des supporters du LOSC.',
    capacity: 120,
    amenities: ['screen', 'bar', 'food'],
    openingHours: '17h-23h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-6',
    name: 'Le Bistrot Sang et Or',
    city: 'Lens',
    address: '5 Place du Cantin, 62300 Lens',
    lat: 50.4289,
    lng: 2.8319,
    teamName: 'RC Lens',
    teamLogo: '🟡',
    description: 'À deux pas du stade Bollaert, l\'endroit incontournable pour les fans du Racing.',
    capacity: 250,
    amenities: ['screen', 'bar', 'food', 'parking'],
    openingHours: '11h-02h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-7',
    name: 'Le Monaco Sports Bar',
    city: 'Monaco',
    address: '3 Avenue Princesse Grace, 98000 Monaco',
    lat: 43.7384,
    lng: 7.4246,
    teamName: 'AS Monaco',
    teamLogo: '🔴',
    description: 'Vue sur la Méditerranée et ambiance VIP pour suivre l\'ASM.',
    capacity: 100,
    amenities: ['screen', 'bar', 'terrace', 'wifi'],
    openingHours: '18h-02h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-8',
    name: 'Le Petit Nice',
    city: 'Nice',
    address: '18 Promenade des Anglais, 06000 Nice',
    lat: 43.6961,
    lng: 7.2650,
    teamName: 'OGC Nice',
    teamLogo: '🦅',
    description: 'Sur la célèbre Promenade, vivez les matchs de l\'OGC Nice face à la mer.',
    capacity: 130,
    amenities: ['screen', 'bar', 'terrace', 'food'],
    openingHours: '16h-01h',
    isVerified: false,
    isActive: true,
  },
  {
    id: 'fz-9',
    name: 'Le Bar Breton',
    city: 'Rennes',
    address: '7 Place Sainte-Anne, 35000 Rennes',
    lat: 48.1173,
    lng: -1.6778,
    teamName: 'Stade Rennais',
    teamLogo: '🔻',
    description: 'Cidre et football : la combo parfaite pour les supporters du Stade Rennais.',
    capacity: 90,
    amenities: ['screen', 'bar', 'wifi'],
    openingHours: '17h-00h',
    isVerified: true,
    isActive: true,
  },
  {
    id: 'fz-10',
    name: 'Le Corsaire',
    city: 'Brest',
    address: '22 Rue de Siam, 29200 Brest',
    lat: 48.3904,
    lng: -4.4861,
    teamName: 'Stade Brestois',
    teamLogo: '🏴',
    description: 'Ambiance bretonne et matchs du SB29 sur grand écran.',
    capacity: 80,
    amenities: ['screen', 'bar', 'food'],
    openingHours: '16h-23h',
    isVerified: false,
    isActive: true,
  },
]

export const metadata = {
  title: 'Fan Zones | SportUnion',
  description: 'Trouvez les meilleurs endroits pour regarder les matchs près de chez vous. Bars, restaurants et fan zones vérifiés.',
}

export default function FanZonesPage() {
  return <FanZonesClient fanZones={mockFanZones} />
}
